import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavbarLeft from "./components/Navbar/NavbarLeft";
import NavbarRight from "./components/Navbar/NavbarRight";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full flex justify-center`}>
        {/* <NavbarRight/> */}
        {children}
        <NavbarLeft/>
      </body>
    </html>
  );
}
